apiVersion: v1
kind: Service
metadata:
  name: acm-kessel-mini-rbac
  namespace: acm-kessel-mini-rbac
  labels:
    app.kubernetes.io/name: mini-rbac
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: acm
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: acm-kessel-mini-rbac
