apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acm-kessel-postgres-data
  namespace: acm-kessel-mini-rbac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
