apiVersion: v1
kind: Secret
metadata:
  name: acm-kessel-relations-api-config
  namespace: acm-kessel-mini-rbac
type: Opaque
stringData:
  config.yaml: |
    server:
      http:
        addr: "0.0.0.0:8000"
        timeout: 1s
        pathprefix: "/api/authz"
      grpc:
        addr: "0.0.0.0:9000"
        timeout: 30s
      minLogLevel: Info
      auth:
        enableAuth: false
    data:
      spiceDb:
        endpoint: "acm-kessel-spicedb.acm-kessel-mini-rbac.svc.cluster.local:50051"
        token: "CHANGE_ME_REPLACE_WITH_RANDOM_KEY"
        schemaFile: "/etc/schema/schema.zed"
        useTLS: false
        fullyConsistent: true
