apiVersion: v1
kind: Secret
metadata:
  name: acm-kessel-inventory-api-config
  namespace: acm-kessel-mini-rbac
type: Opaque
stringData:
  inventory-api-config.yaml: |
    server:
      public_url: http://0.0.0.0:8000
      http:
        address: 0.0.0.0:8000
      grpc:
        address: 0.0.0.0:9000
      pprof:
        enabled: true
    authn:
      allow-unauthenticated: true
    authz:
      impl: kessel
      kessel:
        insecure-client: true
        enable-oidc-auth: false
    consistency:
      default-to-at-least-as-acknowledged: true
    eventing:
      eventer: stdout
    storage:
      max-serialization-retries: 10
      outbox-mode: wal
      database: postgres
      postgres:
        host: acm-kessel-postgres.acm-kessel-mini-rbac.svc.cluster.local
        port: "5432"
        user: inventoryapi
        password: inventoryapipassword
        dbname: inventory
        sslmode: disable
    service:
      use_v1beta2_db: true
    schema:
      repository: in-memory
      in-memory:
        type: json
        path: schema_cache.json
    consumer:
      enabled: true
      bootstrap-servers: acm-kessel-kafka.acm-kessel-mini-rbac.svc.cluster.local:9092
      topic: outbox.event.kessel.tuples
      group-id: inventory-consumer-group
      retry-options:
        consumer-max-retries: 3
        operation-max-retries: 4
        backoff-factor: 5
      auth:
        enabled: false
    log:
      level: "debug"
      livez: true
      readyz: true
